/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_swa_jni_Printer */

#ifndef _Included_de_swa_jni_Printer
#define _Included_de_swa_jni_Printer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_swa_jni_Printer
 * Method:    format
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_swa_jni_Printer_format
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
